---
title: "Obesity measures-Permanova"
author: "Li-Fang Yeo"
date: "2024-12-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```
```{r}
library(magrittr)
library(ANCOMBC)
library(mia)
```
```{r}
devtools::load_all()
```
Command line arguments
```{r}
args <- list(
  optparse::make_option("--east", action="store_true", default=FALSE, help="Exclude Eastern Finland subpopulation [default \"%default\"]"),
  optparse::make_option("--west", action="store_true", default=FALSE, help="Exclude Eastern Finland subpopulation [default \"%default\"]"),
  optparse::make_option("--low", action="store_true", default=FALSE, help="Exclude low GFR [default \"%default\"]"),
  optparse::make_option("--high", action="store_true", default=FALSE, help="Exclude high GFR [default \"%default\"]"),
  optparse::make_option("--detection", type = "numeric", default = 0.1/100, help = "Detection limit [default %default]"),
optparse::make_option("--prevalence", type = "numeric", default = 5/100, help = "Prevalence limit [default %default]")) %>% 
  optparse::OptionParser(option_list = .) %>%
  optparse::parse_args()
```
```{r}
args %>% tibble::enframe(name = "Option", value = "Argument") %>% DT::datatable()
```
Data definition
```{r}
vars <- list(BL_AGE = "Age",
             MEN = "Men",
             BMI = "BMI",
             VYOTARO = "Waist circ",
             WHR = "waist-hip ratio",
             PREVAL_DIAB = "Diabetes",
             PREVAL_CVD = "Cardiovascular disease",
             CURR_SMOKE = "Smoking",
             ALKI2_FR02 = "Alcohol consumption per week (g)",
             HFC = "Healthy food choices",
             Q57X = "Exercise",
             shannon = "Shannon diversity",
             observed = "Richness",
             EAST = "Eastern finland")
```
Read data in and filter for covariates
```{r}
tse <- readRDS("../data/tse_mgs-20241118_104759.rds") %>%
  mia::transformAssay(assay.type = "counts", method = "relabundance") %>% 
  mia::addAlpha(assay.type = "counts", index = c("shannon", "observed"), name = c("shannon", "observed")) %>%
  tse_add_food_score(HFC) %>%
  #combine values into one
  tse_mutate(Q57X = dplyr::if_else(Q57X %in% c(3, 4), 3, Q57X)) %>%
  tse_mutate(dplyr::across(c(MEN,
                             CURR_SMOKE,
                             EAST,
                             Q57X,
                             dplyr::contains("INCIDENT"),
                             dplyr::contains("PREVAL")), as.factor)) %>% 
  #pregnant
  tse_filter(GRAVID %in% c(1, NA)) %>%
  #antibiotic use in the past 1 month
  tse_filter(BL_USE_RX_J01_1mo %in% c(0, NA)) %>%
  #missing covariate
  tse_filter(dplyr::if_all(dplyr::one_of(names(vars)), not_na)) %>%
  #low reads
  tse_filter(total_reads > 50000) %>%
  tse_select(names(vars))
```
# Characteristic
```{r}
tse %>%
  tse_meta(rownames = FALSE) %>%
  dplyr::mutate(EAST = factor(ifelse(EAST == 1, "Eastern Finland" , "Western Finland"))) %>%
  mytableone(vars,fo =  ~ .| EAST )

```
# Beta diversity
Calculate RDA using Bray-curtis at the species level with only age and sex covariates
```{r}
tse <- tse %>%  mia::agglomerateByRank(rank = "Species") %>% 
  mia::transformAssay(method = "relabundance") %>%
  mia::getPERMANOVA(assay.type = "relabundance",
                 method = "bray",
                 na.action = na.exclude,
                 formula = assay ~ BL_AGE + MEN + PREVAL_DIAB + 
                                PREVAL_CVD + CURR_SMOKE +
                                ALKI2_FR02 + HFC + Q57X + BMI)


permanova <- mia::getPERMANOVA(tse, assay.type= "relabundance",
                               formula = assay ~ BL_AGE + MEN + PREVAL_DIAB + 
                                PREVAL_CVD + CURR_SMOKE +
                                ALKI2_FR02 + HFC + Q57X + BMI )
```

```{r}
rda_info <- attr(SingleCellExperiment::reducedDim(tse, "RDA"), "significance")

```
```{r}
rda_info$permanova %>%
 knitr::kable() %>%
 write.csv("./permanova/permanova-bmi2.csv")
rda_info$homogeneity %>%  
 knitr::kable() %>%
 write.csv("./permanova/homogeneity-bmi2.csv")
```
ANOVA model
```{r}
rda_info$permanova %>% 
  knitr::kable()
```
```{r}
tse <-  tse %>%  mia::agglomerateByRank(rank = "Species") %>% 
  mia::transformAssay(method = "relabundance") %>%
  mia::addRDA(assay.type = "relabundance",
                 method = "bray",
                 na.action = na.exclude,
                 formula = assay ~ BL_AGE + MEN + PREVAL_DIAB + 
                                PREVAL_CVD + CURR_SMOKE +
                                ALKI2_FR02 + HFC + Q57X + BMI)

rda_info <- attr(reducedDim(tse, "RDA"), "significance")

library(miaViz)
colData(tse)$BMI_Category <- cut(colData(tse)$BMI,
                      breaks = c(-Inf, 18.5, 24.9, 29.9, 39.9, Inf),
                      labels = c("Underweight (n=40)", "Normal (n=2137)", 
                                 "Overweight (n=2401)", "Obese (n=1202)", 
                                 "Morbid Obesity (n=66)"))
rda_plot <- plotRDA(tse, "RDA", colour.by = "BMI_Category", add.vectors = FALSE)
my_colors <- c("#d4a1a1", "#FFCC00", "#FF9900",  "#990000", "black")
rda_plot <- rda_plot + scale_color_manual(values = my_colors)
plot(rda_plot)
ggplot2::ggsave(filename = "RDA_BMI_1.pdf", 
                plot = rda_plot,
                #dpi = 300,
                width = 10,
                height = 8,
                units = "in" )

```
```{r}
rda_info$permanova |>
   knitr::kable()

```

