---
title: "Functional Obesity Microbiome"
author: "LF Yeo"
date: "05-June-2025"
output: html_document
---
```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message=FALSE) 
```
```{r, echo = FALSE}
library(magrittr)
library(dplyr)
library(readr)
library(mia)
devtools::load_all()
```
Command line arguments
```{r}
args <- list(
  optparse::make_option("--east", action="store_true", default=FALSE, help="Exclude Eastern Finland subpopulation [default \"%default\"]"),
  optparse::make_option("--west", action="store_true", default=TRUE, help="Exclude Western Finland subpopulation [default \"%default\"]"),
  optparse::make_option("--detection", type = "numeric", default = 0.1/100, help = "Detection limit [default %default]"),
optparse::make_option("--prevalence", type = "numeric", default = 5/100, help = "Prevalence limit [default %default]")) %>% 
  optparse::OptionParser(option_list = .) %>%
  optparse::parse_args()
```
```{r}
args %>% tibble::enframe(name = "Option", value = "Argument") %>% DT::datatable()
```

```{r}
#Defining covariates for the model
vars <- list(BL_AGE = "Age",
             MEN = "Men",
             BMI = "BMI",
             VYOTARO = "Waist circ",
             WHR = "waist-hip ratio",
             PREVAL_DIAB = "Diabetes",
             PREVAL_CVD = "Cardiovascular disease",
             CURR_SMOKE = "Smoking",
             ALKI2_FR02 = "Alcohol consumption per week (g)",
             HFC = "Healthy food choices",
             Q57 = "Exercise",
             observed = "Observed richness",
             shannon = "Shannon diversity",
             total_reads = "Total reads",
             FID = "Family ID",
             EAST = "Eastern finland",
             Sample_ID.col_from_pheno ="IID")

#Importing metadata and cleaning up
#needed to match SampleID and covariates
tse <- readRDS("data/tse_mgs-20241118_104759.rds") %>%
  mia::transformAssay(assay.type = "counts", method = "relabundance") %>% 
  mia::addAlpha(assay.type = "counts", index = c("shannon", "observed"), name = c("shannon", "observed")) %>%
  tse_add_food_score(HFC) %>%
  #combine values into one
  tse_mutate(Q57 = dplyr::if_else(Q57 %in% c(3, 4), 3, Q57)) %>%
  tse_mutate(dplyr::across(c(MEN,
                             CURR_SMOKE,
                             EAST,
                             Q57,
                             dplyr::contains("INCIDENT"),
                             dplyr::contains("PREVAL")), as.factor)) %>% 
  #pregnant
  tse_filter(GRAVID %in% c(1, NA)) %>%
  #antibiotic use in the past 1 month
  tse_filter(BL_USE_RX_J01_1mo %in% c(0, NA)) %>%
  #missing covariate
  tse_filter(dplyr::if_all(dplyr::one_of(names(vars)), not_na)) %>%
  #low reads
  tse_filter(total_reads > 50000) %>%
  tse_select(names(vars))

tse1 <- tse %>%
    #filter for eastern finland
  { if (args$east) tse_filter(., EAST == 0) else . } %>% 
  { if (args$west) tse_filter(., EAST == 1) else . } %>% 
  tse_select(names(vars))
```
#Command line arguments
```{r}
args <- list(
  optparse::make_option("--east", action="store_true", default=TRUE, help="Exclude Eastern Finland subpopulation [default \"%default\"]"),
  optparse::make_option("--west", action="store_true", default=FALSE, help="Exclude Western Finland subpopulation [default \"%default\"]"),
  optparse::make_option("--detection", type = "numeric", default = 0.1/100, help = "Detection limit [default %default]"),
  optparse::make_option("--prevalence", type = "numeric", default = 5/100, help = "Prevalence limit [default %default]")) %>% 
  optparse::OptionParser(option_list = .) %>%
  optparse::parse_args()
```
```{r}
args %>% tibble::enframe(name = "Option", value = "Argument") %>% DT::datatable()
```
```{r}
#turn on east/west
tse2 <- tse %>%
    #filter for eastern finland
  { if (args$east) tse_filter(., EAST == 0) else . } %>% 
  { if (args$west) tse_filter(., EAST == 1) else . } %>% 
  tse_select(names(vars))

```

```{r}
#Functional pathways from metaCyc
joined_pathabundance <- read_delim("../data/joined_pathabundance.tsv", 
                                   delim = "\t", escape_double = FALSE, trim_ws = TRUE)
```
```{r}
#Matching sampleID from functional data to metadata
#rename 1st column name
a <- as.data.frame(colData(tse))%>%
  tibble::rownames_to_column("Barcode")

# Get the column names (excluding the first one, which is probably the path/feature column)
sample_names <- colnames(joined_pathabundance)[-1]

# Clean sample names by removing after .R1
cleaned_sample_names <- gsub("\\.R1.*","", sample_names, perl = TRUE)

# Update the column names with the cleaned sample names
colnames(joined_pathabundance)[-1] <- cleaned_sample_names

# Find the intersection of sample names between the cleaned joined_path_abundance sample names and FINRISK sample data
common_samples <- intersect(a$Barcode, cleaned_sample_names)

# Subset the joined_pathabundance file to include only the common samples
shit <- joined_pathabundance %>%
  select(all_of(c("Pathway", common_samples))) %>% 
  filter(rowSums(across(where(is.numeric))) != 0) %>%
  filter(!grepl("\\|g_", Pathway)) %>%
  filter(!grepl("superpathway", Pathway)) %>%
  filter(!grepl("fungi", Pathway)) %>%
  filter(!grepl("plant", Pathway)) %>%
  filter(!grepl("eukaryotes", Pathway)) %>%
  filter(!grepl("yeast", Pathway))
```
Transpose dataframe
```{r}
shit.t <- as.data.frame(t(shit))
#take first row as colname
colnames(shit.t) <- shit.t[1,]
#remove extra row
shit.t <- shit.t[-1, ] 
#change from character to numeric
shit.t <- shit.t %>% mutate_if(is.character, as.numeric) %>%
  tibble::rownames_to_column("Barcode") 
```
Prevalence filtering
```{r}
#You will get a dataframe of prevalent pathways
#poo needs to have samples as row, pathways as column
shit.10 <- shit.t %>% 
  select(-1) %>%
  #mutate to 1 for everything > 0.0000000001
  mutate(across(everything(), ~ . > 1e-10)) %>%
  #get proportion
  summarize(across(everything(), mean)) %>%
  tidyr::gather(Pathway,prevalence) %>%
  #filter for pathways that are prevalent in 5%
  dplyr::filter(prevalence >0.05) 

# filtered to only prevalent pathways
hi <- shit.10 %>% 
  select(-2) %>%
  dplyr::inner_join(shit, by="Pathway" ) %>%
  t() %>%
  as.data.frame()

#take first row as colname
colnames(hi) <- hi[1,]
#remove extra row
hi <- hi[-1, ] 
#change from character to numeric
hi <- hi %>% mutate_if(is.character, as.numeric) %>%
  tibble::rownames_to_column("Barcode") 
```
Reduce to dichotomous variables (absence / presence)
```{r}
#Get df that has prevalence filtered pathway
#Dichotomise
poo_dicho <- hi %>% 
  mutate(across(where(is.numeric), ~ ifelse(. > 0.000, 1, 0)))
```
join functional data to metadata
```{r}
#Match samples with (filtered) tse
east <- as.data.frame(colData(tse1))%>%
  tibble::rownames_to_column("Barcode")

west <- as.data.frame(colData(tse2))%>%
  tibble::rownames_to_column("Barcode")

df <- dplyr::right_join(poo_dicho, east, by = "Barcode")
```
```{r}
lm_full_bmi_partial <-  purrr::partial(lm,
                                  formula = BMI ~
                                    scale(term) + BL_AGE + MEN +
                                    PREVAL_DIAB + PREVAL_CVD + CURR_SMOKE +
                                    ALKI2_FR02 + HFC + Q57) %>%
                    purrr::possibly()

lm_bmi_partial <-  purrr::partial(lm,
                                  formula = BMI ~
                                    scale(term) + BL_AGE + MEN) %>%
                    purrr::possibly()
```
```{r}
#Take the column names from Pathway in shit dataframe as a list and mutate
try <- shit.10 %>% 
  dplyr::select(Pathway) %>% 
  dplyr::mutate(results = purrr::map(Pathway, ~lm_full_bmi_partial(data = df %>% dplyr::rename(term=.x)), .progress = TRUE))

try%>% 
  dplyr::filter(!is.na(results)) %>%
  dplyr::mutate(results = purrr::map(results, ~broom::tidy(.x, conf.int = TRUE)))  %>%
  tidyr::unnest(results) %>%
  dplyr::filter(term == "scale(term)") %>%
  dplyr::mutate(qval_fdr = p.adjust(p.value, method = "BH")) %>%
  dplyr::arrange(p.value) %>%
  dplyr::filter(qval_fdr < 0.05) %>%
  dplyr::mutate_if(is.numeric, ~round(.x, digits = 4)) %>%
  DT::datatable(caption = "Linear model for MetaCyc pathways - discovery east, multivariate-adj")
```
```{r}
#take only significant pathway in discovery cohort
sig <- try%>% 
  dplyr::filter(!is.na(results)) %>%
  dplyr::mutate(results = purrr::map(results, ~broom::tidy(.x, conf.int = TRUE)))  %>%
  tidyr::unnest(results) %>%
  dplyr::filter(term == "scale(term)") %>%
  dplyr::mutate(qval_fdr = p.adjust(p.value, method = "BH")) %>%
  dplyr::arrange(p.value) %>%
  dplyr::filter(qval_fdr < 0.05) %>%
  dplyr::select(Pathway)

#Validation
#Pathway dataframe to match east samples
west <- as.data.frame(colData(tse2))%>%
  tibble::rownames_to_column("Barcode")

df <- dplyr::right_join(poo_dicho, west, by = "Barcode")

only_sig <- sig %>% 
  dplyr::mutate(results = purrr::map(Pathway, ~lm_full_bmi_partial(data = df %>% dplyr::rename(term=.x)), .progress = TRUE))

only_sig %>% 
  dplyr::filter(!is.na(results)) %>%
  dplyr::mutate(results = purrr::map(results, ~broom::tidy(.x, conf.int = TRUE)))  %>%
  tidyr::unnest(results) %>%
  dplyr::filter(term == "scale(term)") %>%
  dplyr::mutate(qval_fdr = p.adjust(p.value, method = "BH")) %>%
  dplyr::arrange(p.value) %>%
  dplyr::filter(qval_fdr < 0.05) %>%
  dplyr::mutate_if(is.numeric, ~round(.x, digits = 4)) %>%
  #write.csv("function_dicho.csv")
  DT::datatable(caption = "Linear model for MetaCyc pathways - validation west, multivariable-adj")
```
Tranform to inverse_rank
```{r}
# Define the transformation function
transform_column <- function(x) {
  qnorm((rank(x, na.last = "keep") - 0.5) / sum(!is.na(x)))
}

# Apply the transformation to all columns
poo_rank <- hi
poo_rank[, -1] <- lapply(hi[, -1], transform_column)
```
Data wrangling to join functional data to metadata
```{r}
#Here you will have the correct number of samples
df <- dplyr::right_join(poo_rank, east, by = "Barcode")

##Linear model for inverse rank
#Take the column names from Pathway in shit dataframe as a list and mutate
try <- shit.10 %>% 
  dplyr::select(Pathway) %>% 
  dplyr::mutate(results = purrr::map(Pathway, ~lm_full_bmi_partial(data = df %>% dplyr::rename(term = .x)), .progress = TRUE))

try%>% 
  dplyr::filter(!is.na(results)) %>%
  dplyr::mutate(results = purrr::map(results, ~broom::tidy(.x, conf.int = TRUE)))  %>%
  tidyr::unnest(results) %>%
  dplyr::filter(term == "scale(term)") %>%
  dplyr::mutate(qval_fdr = p.adjust(p.value, method = "BH")) %>%
  dplyr::arrange(p.value) %>%
  dplyr::filter(qval_fdr < 0.05) %>%
  dplyr::mutate_if(is.numeric, ~round(.x, digits = 4)) %>%
  DT::datatable(caption = "Linear model Inverse Rank Normalised for MetaCyc pathways - discovery east")
```
```{r}
#Here you will have the correct number of samples
df <- dplyr::right_join(poo_rank, west, by = "Barcode")

#take only significant pathway in discovery cohort
sig <- try%>% 
  dplyr::filter(!is.na(results)) %>%
  dplyr::mutate(results = purrr::map(results, ~broom::tidy(.x, conf.int = TRUE)))  %>%
  tidyr::unnest(results) %>%
  dplyr::filter(term == "scale(term)") %>%
  dplyr::mutate(qval_fdr = p.adjust(p.value, method = "BH")) %>%
  dplyr::arrange(p.value) %>%
  dplyr::filter(qval_fdr < 0.05) %>%
  dplyr::select(Pathway)
```
```{r}
##Linear model for inverse rank
#Take the column names from Pathway in shit dataframe as a list and mutate
only_sig <- sig %>%
  dplyr::mutate(results = purrr::map(Pathway, ~lm_full_bmi_partial(data = df %>% dplyr::rename(term = .x)), .progress = TRUE))

only_sig %>% 
  dplyr::filter(!is.na(results)) %>%
  dplyr::mutate(results = purrr::map(results, ~broom::tidy(.x, conf.int = TRUE)))  %>%
  tidyr::unnest(results) %>%
  dplyr::filter(term == "scale(term)") %>%
  dplyr::mutate(qval_fdr = p.adjust(p.value, method = "BH")) %>%
  dplyr::arrange(p.value) %>%
  dplyr::filter(qval_fdr < 0.05) %>%
  dplyr::mutate_if(is.numeric, ~round(.x, digits = 4)) %>%
  write.csv("functional-IRN.csv")
  DT::datatable(caption = "Linear model for Inverse Rank MetaCyc pathways - validation west, multi-adj")
```


